wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 50
hidden_dim:
  value: 256
learning_rate:
  value: 0.0018618537660768323
num_layers:
  value: 4
readout:
  value: sum
use_bond_features:
  value: true
weight_decay:
  value: 0.0001
