wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 50
hidden_dim:
  value: 128
learning_rate:
  value: 0.004479014999886262
num_layers:
  value: 3
readout:
  value: max
use_bond_features:
  value: false
weight_decay:
  value: 0.0001
