wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 50
hidden_dim:
  value: 64
learning_rate:
  value: 0.00010614058088175254
num_layers:
  value: 2
readout:
  value: sum
use_bond_features:
  value: false
weight_decay:
  value: 0.0001
