wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 50
hidden_dim:
  value: 256
learning_rate:
  value: 0.003315449039115689
num_layers:
  value: 2
readout:
  value: max
use_bond_features:
  value: false
weight_decay:
  value: 0.0001
